# Generated by Django 2.2.3 on 2019-09-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=255, unique=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Pedido_articulo', to='articulos.Articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Pedido_cliente', to='clientes.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Pedido_estado', to='pedidos.Estado')),
            ],
        ),
    ]
