# Generated by Django 2.2.3 on 2019-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190911_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
