# Generated by Django 2.1.12 on 2019-09-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('pedidos', '0003_pedido_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PedidoArticulo_articulo', to='articulos.Articulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='pedidoarticulo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PedidoArticulo_pedido', to='pedidos.Pedido'),
        ),
    ]
